version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
  working_directory: ~/grunt-axe-webdriver

configure_npm: &configure_npm
  run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
      - <<: *configure_npm
      - run: npm install
      - save_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
      # This makes sure Chrome is always up to date in your test suite
      # On average this adds about 10 seconds to your build suite
      # Requires Ubuntu 14.04 (Trusty) in the CircleCI's OS setting (Settings > Build Environment)
      #
      # TODO: cache this or use a Docker image that already contains an up-to-date Chrome
      - run:
          name: Update Chrome
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt-get install libappindicator3-1
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run: npm test
  release:
    <<: *defaults
    steps:
      - checkout
      - <<: *configure_npm
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - tests:
          requires:
            - dependencies
      - release:
          requires:
            - dependencies
            - tests
          filters:
            branches:
              only: master
